# Google Cloud SDK plugin
# Sources the PATH and shell completion helpers generated by the SDK installer.

GCLOUD_SDK="$HOME/google-cloud-sdk"

[[ -f "$GCLOUD_SDK/path.zsh.inc" ]]       && source "$GCLOUD_SDK/path.zsh.inc"
[[ -f "$GCLOUD_SDK/completion.zsh.inc" ]] && source "$GCLOUD_SDK/completion.zsh.inc"
