[env]
TERM = "alacritty"

[font]
size = 10.0

[keyboard]
bindings = [
  { action = "Copy", key = "C", mods = "Control|Shift" },
  { action = "Paste", key = "V", mods = "Control|Shift" }
]

[window]
opacity = 0.9

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

# Catppuccin Macchiato

[colors.primary]
background = '#24273a'
foreground = '#cad3f5'

[colors.normal]
black = '#494d64'
red = '#ed8796'
green = '#a6da95'
yellow = '#eed49f'
blue = '#8aadf4'
magenta = '#f5bde6'
cyan = '#8bd5ca'
white = '#b8c0e0'

[colors.bright]
black = '#5b6078'
red = '#ed8796'
green = '#a6da95'
yellow = '#eed49f'
blue = '#8aadf4'
magenta = '#f5bde6'
cyan = '#8bd5ca'
white = '#a5adcb'
