[env]
TERM = "xterm-256color"

[font]
size = 10.0

[shell]
program = "C:\Windows\System32\wsl.exe"
args = ["~", "-d", "debian"]

[keyboard]
bindings = [
  { action = "Copy", key = "C", mods = "Control|Shift" },
  { action = "Paste", key = "V", mods = "Control|Shift" }
]

[window]
opacity = 0.9

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

# GNOME Terminal Tango Dark

[colors.primary]
background = '#2e3436'
foreground = '#d3d7cf'

[colors.normal]
black = '#2e3436'
red = '#cc0000'
green = '#4e9a06'
yellow = '#c4a000'
blue = '#3465a4'
magenta = '#75507b'
cyan = '#06989a'
white = '#d3d7cf'

[colors.bright]
black = '#555753'
red = '#ef2929'
green = '#8ae234'
yellow = '#fce94f'
blue = '#729fcf'
magenta = '#ad7fa8'
cyan = '#34e2e2'
white = '#eeeeec'
